- type: department
  id: Law
  name: department-Law
  description: department-Law-description
  color: "#FF5297"
  weight: 80
  roles:
    - Magistrat
    - IAA
    - Lawyer
    - NtrOfficer

- type: department # Fihs-start
  id: BlueShield
  name: department-Blueshield
  description: department-Blueshield-description
  color: "#0f4e81"
  roles:
   - BlueShieldEnsign
   - BlueShieldOfficer
  primary: false
  eight: 50 # Fihs-end

- type: department
  id: PlanetPrison
  sort: 0
  name: department-PlanetPrison
  description: department-PlanetPrison-description
  color: "#9f4000"
  roles:
  - HeadOfPrison
  - PrisonWorker
  - PrisonChef
  - PrisonDoctor
  - PrisonEngineer
  - PrisonGuard
  - PlanetPrisoner

- type: department
  id: CentralCommand
  name: department-CentralCommand
  description: department-CentralCommand-description
  color: "#0d4f1d"
  roles:
  - CentCommOperator
  - CentCommOfficial
  - CentCommOfficer #Fish-edit
  - CentCommTrainee #Fish-edit
  - BlueShieldCentcom #Fish-edit
  weight: 120

- type: department
  id: SpecialOperations
  name: department-SpecialOperations
  description: department-SpecialOperations-description
  color: "#0c344d"
  roles:
  - CBURN
  - ERTLeader
  - ERTChaplain
  - ERTJanitor
  - ERTMedical
  - ERTSecurity
  - ERTEngineer
  - DeathSquad
  editorHidden: true
