- type: job
  id: CentCommTrainee
  name: job-name-centcomtr
  description: job-description-centcomTrainee
  playTimeTracker: JobCentCommTrainee
  requirements:
  - !type:DiscordRoleRequirement
  weight: 30
  setPreference: true
  startingGear: CentCommTraineeGear
  icon: "JobIconNanotrasenTrainee"
  overrideConsoleVisibility: false # Sunrise added
  supervisors: job-supervisors-centcom
  radioBold: true
  canBeAntag: false
  alwaysUseSpawner: true
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: CentCommTraineeGear
  equipment:
    shoes: ClothingShoesBootsCombatFilled
    gloves: ClothingHandsGlovesColorWhite
    # outerClothing: ClothingOuterArmorBasicSlim
    id: CentcomOperatorPDA
    ears: ClothingHeadsetCentCom
  storage:
    back:
    - Paper

# ClothingUniformJumpsuitCentcomOfficer
# ClothingShoesBootsCombatFilled
# ClothingHeadsetCentCom
# ClothingHandsGlovesColorWhite
