- type: job
  id: CentCommOfficer
  name: job-name-centcomoff
  description: job-description-centcomoff
  playTimeTracker: JobCentCommOfficer
  requirements:
  - !type:DiscordRoleRequirement
  weight: 30
  setPreference: false
  startingGear: CentCommOfficerGear
  icon: "JobIconNanotrasen"
  overrideConsoleVisibility: false # Sunrise added
  supervisors: job-supervisors-centcom
  radioBold: true
  canBeAntag: false
  alwaysUseSpawner: true
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: CentCommOfficerGear
  equipment:
    # jumpsuit: ClothingUniformJumpsuitCentcomOfficial #Fish-Edit
    shoes: ClothingShoesBootsCombatFilled
    # head: ClothingHeadHatCentcom  #Fish-Edit
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesColorBlack
    # outerClothing: ClothingOuterArmorCentcomCarapace
    id: CentcomPDA
    ears: ClothingHeadsetAltCentCom
    belt: WeaponPistolN1984
  storage:
    back:
    - PenCentcom
    - BoxFolderBlack
