- type: job # Fish-start
  id: BlueShieldCentcom
  name: job-name-blueshield-officer-centcom
  description: job-description-blueshield-officer-centcom
  playTimeTracker: JobBlueShieldCentcom # Fish-start
  requirements:
   - !type:DepartmentTimeRequirement
     department: Security
     time: 62000 # 20 hrs
   - !type:AgeRequirement
     requiredAge: 30
  startingGear: BlueShieldCentcomGear
  icon: JobIconBlueShield
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
   - Command
   - Bar
   - Service
   - Maintenance
   - Janitor
   - Theatre
   - Kitchen
   - Chapel
   - Hydroponics
   - External
   - Chemistry
   - Engineering
   - Research
   - Salvage
   - Cargo
   - Atmospherics
   - Cargo
   - Medical
   - BlueShield
  special:
   - !type:AddImplantSpecial
     implants: [ MindShieldImplant ]

- type: startingGear
  id: BlueShieldCentcomGear
  equipment:
   shoes: ClothingShoesBootsBlueShieldFilled
   eyes: ClothingEyesGlassesBlueShield
   outerClothing: ClothingOuterArmorBlueShield
   id: BlueShieldOfficerPDA
   ears: ClothingHeadsetBlueShield
   gloves: ClothingHandsGlovesCombat
  storage:
   back:
   - HandheldBSOCrewMonitor
